import { mkdirSync, readdirSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const projectUrl = new URL('../', import.meta.url)
const generatedTypesPath = () => fileURLToPath(new URL('./types/generated.d.ts', projectUrl))

const namesFromDirectory = (directory: URL, extension: string) =>
    readdirSync(fileURLToPath(directory))
        .filter((file) => file.endsWith(extension))
        .map((file) => file.slice(0, -extension.length))
        .sort((a, b) => a.localeCompare(b))

export const svgAssetNames = () =>
    namesFromDirectory(new URL('./server/assets', projectUrl), '.svg')

export const presetNames = () => namesFromDirectory(new URL('./server/presets', projectUrl), '.ts')

export const presetType = () =>
    presetNames()
        .map((name) => `'${name}'`)
        .join(' | ') || 'never'

export const writeGeneratedTypes = () => {
    const imageEntries = svgAssetNames()
        .map((name) => `        readonly ${JSON.stringify(name)}: OgImageAsset<'${name}'>`)
        .join('\n')
    const presets = presetType()
    const outputPath = generatedTypesPath()

    mkdirSync(fileURLToPath(new URL('./types', projectUrl)), { recursive: true })
    writeFileSync(
        outputPath,
        `// This file is generated by scripts/generated-types.ts.
// Do not edit manually.

declare module '#images' {
    interface OgImageAsset<TSrc extends string = string> {
        src: TSrc
        svg: string
    }

    export const images: {
${imageEntries}
    }
}

declare module '#presets' {
    export type Preset = ${presets}
    export const allPresets: readonly (import('../server/utils/definePreset').OgImagePreset & {
        slug: Preset
    })[]
}
`,
    )
}
